# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKkio8qMpRaf5NrW8wkxBGxuyCiHUS6O

Q1. Spark Initialization and Data Loading
"""

from pyspark.sql import SparkSession

# Initialize Spark
spark = SparkSession.builder \
    .appName("PredictiveMaintenancePlatform") \
    .getOrCreate()

print("Spark Version:", spark.version)

# Load Dataset
df = spark.read.csv(
    "/content/machine_data.csv",
    header=True,
    inferSchema=True
)

# Display Dataset
df.show()

# Print Schema
df.printSchema()

# Count Records
print("Total Records:", df.count())

"""Q2. RDD Implementation"""

machine_rdd = df.rdd

print(machine_rdd.collect())

high_temp = machine_rdd.filter(lambda x: x.temperature > 90)

high_temp.collect()

production_rdd = machine_rdd.map(lambda x: (x.machine_id, x.production))

production_rdd.collect()

"""Q3. Key-Value Operations and Persistence"""

production_sum = production_rdd.reduceByKey(lambda a, b: a + b)

production_sum.collect()

production_sum.cache()

production_sum.collect()

production_sum.unpersist()

"""Q4. Spark DataFrame Operations"""

df.select("machine_id", "temperature").show()

df.filter(df.temperature > 90).show()

df.groupBy("machine_id").sum("production").show()

"""Q5. Exploratory Data Analysis and Spark SQL"""

df.createOrReplaceTempView("machines")

df.createOrReplaceTempView("maintenance")

spark.sql("""
SELECT machine_id,
       AVG(temperature) AS AvgTemp,
       SUM(production) AS TotalProduction
FROM machines
GROUP BY machine_id
""").show()

"""Q6. ETL Pipeline Development"""

maintenance_df = df.select("machine_id", "maintenance_cost", "maintenance_date")

joined_df = df.join(
    maintenance_df,
    on="machine_id",
    how="left"
)

joined_df.show()

"""Q7. Machine Learning/Deep Learning Implementation"""

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.classification import LogisticRegression

assembler = VectorAssembler(
    inputCols=["temperature", "vibration", "production"],
    outputCol="features"
)

data = assembler.transform(df)

train, test = data.randomSplit([0.8, 0.2], seed=42)

lr = LogisticRegression(featuresCol="features", labelCol="failure")

model = lr.fit(train)

predictions = model.transform(test)

predictions.select(
    "machine_id",
    "failure",
    "prediction",
    "probability"
).show(truncate=False)

