name: Predictive Maintenance CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: CaseStudyAI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Spark Application
        run: |
          python app.py

      - name: Build Docker Image
        run: |
          docker build -t casestudy .
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get deployments
          kubectl get services
